// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	deposit "github.com/arnaz06/deposit"
	mock "github.com/stretchr/testify/mock"

	pb "github.com/arnaz06/deposit/pb"
)

// DepositRepository is an autogenerated mock type for the DepositRepository type
type DepositRepository struct {
	mock.Mock
}

// Deposit provides a mock function with given fields: ctx, input
func (_m *DepositRepository) Deposit(ctx context.Context, input *pb.Deposit) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.Deposit) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, walletID
func (_m *DepositRepository) Get(ctx context.Context, walletID int64) (deposit.Deposit, error) {
	ret := _m.Called(ctx, walletID)

	var r0 deposit.Deposit
	if rf, ok := ret.Get(0).(func(context.Context, int64) deposit.Deposit); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(deposit.Deposit)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
